In [1]:
import cv2 as cv
import os
import numpy as np
from PIL import Image 
import pickle

In [4]:
img = cv.imread('C:/Users/fikri/Desktop/pyproj/muke/muke/bacan/2.jpg')
cv.imshow('bacan',img)
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY) 
cv.waitKey(0)

-1

In [5]:
haar_cascade = cv.CascadeClassifier('C:/Users/fikri/Desktop/pyproj/muke/data/haarcascade_frontalface_alt2.xml')
face_react = haar_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors = 4)
for (x,y,w,h) in face_react:
    cv.rectangle(img, (x,y),(x+w,y+h),(0,255,0),thickness = 2)
cv.imshow('detected', img)
cv.waitKey(0)

-1

# live 

In [3]:
capture = cv.VideoCapture(0)
haar_cascade = cv.CascadeClassifier('C:/Users/fikri/Desktop/pyproj/muke/data/haarcascade_frontalface_alt2.xml')

recognizer = cv.face.LBPHFaceRecognizer_create()
recognizer.read('trainer.yml')

labels = {"person_name" : 1}
with open('labels.pickle', 'rb') as f:
    og_labels = pickle.load(f)
    labels = {v:k for k,v in og_labels.items()}
while True :
    isTrue , frame = capture.read()
    gray2 = cv.cvtColor(frame, cv.COLOR_BGR2GRAY) 
    face_react2 = haar_cascade.detectMultiScale(gray2, scaleFactor=1.5, minNeighbors = 5)
    for (x,y,w,h) in face_react2:
        roi_gray = gray2[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        id_, conf = recognizer.predict(roi_gray)
        if conf>= 45 and conf <= 90:
            font = cv.FONT_HERSHEY_COMPLEX
            name = labels[id_]
            color = (255,255,255)
            stroke = 2
            cv.putText(frame,name,(x,y-15),font,1,color,stroke,cv.LINE_AA)
            
        cv.rectangle(frame, (x,y),(x+w,y+h),(0,255,0),thickness = 2)
    cv.imshow('video', frame)
    if cv.waitKey(20) & 0xFF==ord('d'):
        break
        
capture.release()
cv.destroyAllWindows()

KeyboardInterrupt: 

In [11]:
capture = cv.VideoCapture(0)

while True :
    isTrue , frame = capture.read()
    cv.imshow('video', frame)
    if cv.waitKey(20) & 0xFF==ord('d'):
        break

capture.release()
cv.destroyAllWindows()

KeyboardInterrupt: 

# face recognition training

In [3]:
dirr = os.path.dirname('C:/Users/fikri/Desktop/pyproj/muke/muke/')
haar_cascade = cv.CascadeClassifier('C:/Users/fikri/Desktop/pyproj/muke/data/haarcascade_frontalface_alt2.xml')

recognizer = cv.face.LBPHFaceRecognizer_create()
recognizer.read('trainer.yml')
curr_id = 0
labels_id = {}
y_labels = []
x_train = []

for root, dirs, files in os.walk(dirr):
    for file in files:
        if file.endswith('png') or file.endswith('jpg'):
            path = os.path.join(root , file)
            label = os.path.basename(os.path.dirname(path).replace(" ","-").lower())
            if not label in labels_id:
                labels_id[label] = curr_id
                curr_id += 1
            id_  = labels_id[label]
            print(labels_id)
            #y_labels.append(label)
            #x_train.append(path)
            pil_image = Image.open(path).convert('L')
            image_array = np.array(pil_image, "uint8")
            print(image_array)
            face = haar_cascade.detectMultiScale(image_array, scaleFactor=1.5, minNeighbors = 5)
            for (x,y,w,h) in face:
                roi = image_array[y:y+h, x:x+w]
                x_train.append(roi)
                y_labels.append(id_)
print(x_train)
print(y_labels)
with open('labels.pickle', 'wb') as f:
    pickle.dump(labels_id,f)
recognizer.train(x_train,np.array(y_labels))
recognizer.save('trainer.yml')

                

{'ajohnny-depp': 0}
[[57 57 56 ... 57 58 59]
 [57 57 56 ... 57 58 59]
 [57 57 56 ... 58 58 58]
 ...
 [65 65 65 ... 70 71 71]
 [65 65 65 ... 69 70 70]
 [65 65 65 ... 68 69 70]]
{'ajohnny-depp': 0}
[[143 143 143 ... 170 169 171]
 [143 143 143 ... 170 170 171]
 [143 143 143 ... 171 171 171]
 ...
 [ 60  60  61 ... 170 174 180]
 [ 59  59  59 ... 172 176 182]
 [ 59  59  60 ... 174 179 184]]
{'ajohnny-depp': 0}
[[ 44  44  44 ... 103  98  95]
 [ 44  44  44 ... 104 100  98]
 [ 44  44  44 ... 106 104 104]
 ...
 [144 144 144 ... 167 167 167]
 [144 144 144 ... 179 179 179]
 [144 144 144 ... 196 197 197]]
{'ajohnny-depp': 0}
[[183 183 183 ... 114 114 114]
 [183 183 183 ... 114 114 114]
 [183 183 183 ... 114 114 114]
 ...
 [162 159 155 ... 254 254 254]
 [162 159 155 ... 254 254 254]
 [162 159 155 ... 254 254 254]]
{'ajohnny-depp': 0, 'bacan': 1}
[[84 84 84 ... 84 84 84]
 [84 84 84 ... 84 84 84]
 [84 84 84 ... 84 84 84]
 ...
 [10 10 10 ... 30 30 30]
 [10 10 10 ... 30 30 30]
 [10 10 10 ... 30 30 30]]


In [5]:
label

NameError: name 'label' is not defined